/*
 * File : JFrameUtama.java
 * Deskripsi : GUI untuk mengelola data mahasiswa
 * Pembuat : Muhammad Rofad Hamdani/24060124130117
 * Tanggal : 2 Juni 2026
 */

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import jdbc.model.Mahasiswa;
import jdbc.service.MysqlMahasiswaService;

/**
 *
 * @author LENOVO
 */
public class JFrameUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameUtama.class.getName());
    private MysqlMahasiswaService service;
    private boolean sync = false;

    /**
     * Creates new form JFrameUtama
     */
    public JFrameUtama() throws SQLException {
        initComponents();
        service = new MysqlMahasiswaService();
        loadMahasiswaList();
        jListID.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && !sync){
                updateTextFieldsFromIndex(jListID.getSelectedIndex());
            }});
        jListNama.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && !sync){
                updateTextFieldsFromIndex(jListNama.getSelectedIndex());
            }});
    }

    private void loadMahasiswaList() throws SQLException{
        DefaultListModel<String> namaModel = new DefaultListModel<>();
        DefaultListModel<String> idModel = new DefaultListModel<>();
        List<Mahasiswa> mahasiswaList = service.getAll();
        for (Mahasiswa mhs : mahasiswaList){
            namaModel.addElement(mhs.getNama());
            idModel.addElement(String.valueOf(mhs.getId()));
        }

        jListNama.setModel(namaModel);
        jListID.setModel(idModel);

    }
    
    private void updateTextFieldsFromIndex(int index) {
        if (index == -1){
            return;
        }
        DefaultListModel<String> idModel = (DefaultListModel<String>) jListID.getModel();
        DefaultListModel<String> namaModel = (DefaultListModel<String>) jListNama.getModel();
        if (index >= idModel.getSize() || index >= namaModel.getSize()){
            return;
        }

        String selectedId = idModel.getElementAt(index);
        String selectedName = namaModel.getElementAt(index);
        sync = true;
        try{
            jListID.setSelectedIndex(index);
            jListNama.setSelectedIndex(index);
        }
        finally{
            sync = false;
        }
        jTextFieldEditID.setText(selectedId);
        jTextFieldEditNama.setText(selectedName);
        jTextFieldHapusID.setText(selectedId);
        jTextFieldHapusNama.setText(selectedName);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListID = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNama = new javax.swing.JList<>();
        jLabelID = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jButtonAmbilSemuaData = new javax.swing.JButton();
        jTextFieldInputNama = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jLabelInputNama = new javax.swing.JLabel();
        jTextFieldEditID = new javax.swing.JTextField();
        jTextFieldEditNama = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jTextFieldHapusID = new javax.swing.JTextField();
        jTextFieldHapusNama = new javax.swing.JTextField();
        jButtonHapus = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jLabelJudul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setViewportView(jListID);

        jScrollPane2.setViewportView(jListNama);

        jLabelID.setText("ID");

        jLabelNama.setText("NAMA");

        jButtonAmbilSemuaData.setText("Ambil Semua Data");
        jButtonAmbilSemuaData.addActionListener(this::jButtonAmbilSemuaDataActionPerformed);

        jButtonAdd.setText("Tambahkan");
        jButtonAdd.addActionListener(this::jButtonAddActionPerformed);

        jLabelInputNama.setText("Nama :");

        jTextFieldEditID.setActionCommand("<Not Set>");
        jTextFieldEditID.addActionListener(this::jTextFieldEditIDActionPerformed);

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(this::jButtonEditActionPerformed);

        jTextFieldHapusID.addActionListener(this::jTextFieldHapusIDActionPerformed);

        jTextFieldHapusNama.addActionListener(this::jTextFieldHapusNamaActionPerformed);

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(this::jButtonHapusActionPerformed);

        jButtonReset.setText("Reset Indeks");
        jButtonReset.addActionListener(this::jButtonResetActionPerformed);

        jLabelJudul.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelJudul.setText("Kelola Data Mahasiswa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAmbilSemuaData)
                    .addComponent(jLabelInputNama)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonReset)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEditID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldHapusID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEditNama, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldHapusNama, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEdit)
                            .addComponent(jButtonHapus)))
                    .addComponent(jTextFieldInputNama))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabelJudul))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabelNama)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAdd, jButtonAmbilSemuaData, jButtonReset});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonEdit, jButtonHapus});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelID)
                            .addComponent(jLabelNama))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelJudul)
                        .addGap(22, 22, 22)
                        .addComponent(jButtonAmbilSemuaData)
                        .addGap(15, 15, 15)
                        .addComponent(jLabelInputNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldInputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAdd)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldEditID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(jTextFieldHapusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jTextFieldEditNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldHapusNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonHapus)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jButtonReset)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        String idStr = jTextFieldHapusID.getText();

        if (idStr.isEmpty()){
            JOptionPane.showMessageDialog(this, "ID tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            int id = Integer.parseInt(idStr);
            service.delete(id);
            loadMahasiswaList();
            jTextFieldHapusID.setText("");
            jTextFieldHapusNama.setText("");
            jTextFieldEditID.setText("");
            jTextFieldEditNama.setText("");
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "ID harus berupa angka", "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch (SQLException ex){
            Logger.getLogger(JFrameUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jTextFieldEditIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditIDActionPerformed

    private void jButtonAmbilSemuaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmbilSemuaDataActionPerformed
        try{
            loadMahasiswaList();
        }
        catch (SQLException ex) {
            Logger.getLogger(JFrameUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAmbilSemuaDataActionPerformed

    private void jTextFieldHapusIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHapusIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHapusIDActionPerformed

    private void jTextFieldHapusNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHapusNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHapusNamaActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        String idStr = jTextFieldEditID.getText();
        String nama = jTextFieldEditNama.getText();

        if (idStr.isEmpty()){
            JOptionPane.showMessageDialog(this, "ID tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (nama.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try{
            int id = Integer.parseInt(idStr);
            Mahasiswa mhs = new Mahasiswa();
            mhs.setId(id);
            mhs.setNama(nama);
            service.update(mhs);
            loadMahasiswaList();
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "ID harus berupa angka", "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch (SQLException ex){
            Logger.getLogger(JFrameUtama.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error updating mahasiswa: " + ex.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        String nama = jTextFieldInputNama.getText();

        if (nama.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            service.add(nama);
            loadMahasiswaList();
            jTextFieldInputNama.setText("");
        }
        catch (SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal menambahkan mahasiswa", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        try{
            service.indexReset();
            loadMahasiswaList();
            // Add a success message
            JOptionPane.showMessageDialog(this,
                    "Indeks berhasil direset. ID untuk data baru akan dimulai dari 1.",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error resetting index: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex){
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex){
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex){
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(() -> {
            try{
                new JFrameUtama().setVisible(true);
            }
            catch (SQLException ex){
                Logger.getLogger(JFrameUtama.class.getName()).log(Level.SEVERE, null, ex);
            }});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAmbilSemuaData;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelInputNama;
    private javax.swing.JLabel jLabelJudul;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JList<String> jListID;
    private javax.swing.JList<String> jListNama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldEditID;
    private javax.swing.JTextField jTextFieldEditNama;
    private javax.swing.JTextField jTextFieldHapusID;
    private javax.swing.JTextField jTextFieldHapusNama;
    private javax.swing.JTextField jTextFieldInputNama;
    // End of variables declaration//GEN-END:variables
}
